### ISSUE TITLE
Box is not empty but "No Plans" are available

### ISSUE THREAD

**Issue by allen-cantrell** [danciucu/Radical#12]
https://github.com/danciucu/Radical/blob/b7e2a89cfd4862dfafe44af4bb64dc7233e0c17e/downloadfiles.py#L188

while loop that searches for "No Plans" in button attribute value instead of waiting for file to be downloaded which may be stuck in infinite loop looking for downloaded file.

**Comment by danciucu** [comment]
Solved it!
