### ISSUE TITLE
Update download checkboxes

### ISSUE THREAD

**Issue by allen-cantrell** [danciucu/Radical#5]
https://github.com/danciucu/Radical/blob/25e7da4aee624e621a7befe1e4fedca8d89b7cd0/main.py#L53-L67

## Photo Document checkbox
        self.var1 = tkinter.IntVar()
        self.cbox1 = tkinter.ttk.Checkbutton(self.main_frame, text = 'Photo Document', variable = self.var1, onvalue = 1, offvalue = 0)
        self.cbox1.grid(row = 10, column = 1, sticky = 'w')
        ## Plans checkbox
        self.var2 = tkinter.IntVar()
        self.cbox2 = tkinter.ttk.Checkbutton(self.main_frame, text = 'Plans', variable = self.var2, onvalue = 1, offvalue = 0)
        self.cbox2.grid(row = 11, column = 1, sticky = 'w')
        ## Report Document label
        self.report_label = tkinter.ttk.Label(self.main_frame, text = 'Reports', font = "Arial 12 underline")
        self.report_label.grid(row = 12, column = 1, sticky = 'w')
        ## Previous Report checkbox
        self.var3 = tkinter.IntVar()
        self.cbox3 = tkinter.ttk.Checkbutton(self.main_frame, text = 'Save to Previous Reports folder', variable = self.var3, onvalue = 1, offvalue = 0)
        self.cbox3.grid(row = 13, column = 1, sticky = 'w')
        ## Report Document - Do Not Move After Download checkbox
        self.var4 = tkinter.IntVar()
        self.cbox4 = tkinter.ttk.Checkbutton(self.main_frame, text = 'Save to Report folder', variable = self.var4, onvalue = 1, offvalue = 0)
        self.cbox4.grid(row = 14, column = 1, sticky = 'w')
        ## Report Document - Do Not Move After Download checkbox
        self.var5 = tkinter.IntVar()
        self.cbox5 = tkinter.ttk.Checkbutton(self.main_frame, text = 'Save to Downloads folder', variable = self.var5, onvalue = 1, offvalue = 0)
        self.cbox5.grid(row = 15, column = 1, sticky = 'w')

**Comment by danciucu** [comment]
Issue solved.
