### ISSUE TITLE
Add cb5 if statement

### ISSUE THREAD

**Issue by allen-cantrell** [danciucu/Radical#7]
https://github.com/danciucu/Radical/blob/25e7da4aee624e621a7befe1e4fedca8d89b7cd0/downloadfiles.py#L47

# download current inspection reports to Downloads folders
if globalvars.cb5var == 1:
    self.download_reports(driver)

**Comment by danciucu** [comment]
I think this is not useful since I will allow the user to change the downloading folder via settings.

**Comment by danciucu** [comment]
Not needed anymore.
