### ISSUE TITLE
Move downloaded report to Previous Report or Report based on checkbox

### ISSUE THREAD

**Issue by allen-cantrell** [danciucu/Radical#9]
https://github.com/danciucu/Radical/blob/25e7da4aee624e621a7befe1e4fedca8d89b7cd0/downloadfiles.py#L303

    # If Save to Previous Reports checkbox is checked
            if globalvars.cb3var == 1:
                shutil.move('C:/Users/' + globalvars.user_path + '/Downloads/' + str(globalvars.bridgeID[i]) + ' BrM Report_' + date + '.pdf', globalvars.folders[i])
            # If Save to Report checkbox is checked
            if globalvars.cb4var == 1:
                # If an existing current report exists, move existing report to 'old' folder
                # globalvars.rfolders[i] index is out of range if file already exists in this directory. Need to redefine global.rfolders[i] to match current Bridge ID if file already exists
                if os.path.exists(globalvars.rfolders[i] + '/' + str(globalvars.bridgeID[i]) + ' BrM Report_' + date + '.pdf'):
                    shutil.move(globalvars.rfolders[i] + '/' + str(globalvars.bridgeID[i]) + ' BrM Report_' + date + '.pdf',globalvars.rfolders[i] + '/old')
                    time.sleep(1)
                shutil.move('C:/Users/' + globalvars.user_path + '/Downloads/' + str(globalvars.bridgeID[i]) + ' BrM Report_' + date + '.pdf', globalvars.rfolders[i])

**Comment by danciucu** [comment]
Issue implicitly solved by allowing the user to play with the settings.
